version: '3.8'
services:
  mariadb:
    image: mariadb:10.11
    container_name: fantasy_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lecfantasy
      MYSQL_USER: fantasy_user
      MYSQL_PASSWORD: fantasypassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
