# Esto hace que Spring cree las tablas automáticamente basadas en el código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.file.name=app.log
logging.level.com.lecfantasy.backend=DEBUG

# Desactiva la sesión por defecto para evitar el error de "Lazy Loading"
spring.jpa.open-in-view=false

# Activa el perfil de desarrollo
spring.profiles.active=dev

# Clave secreta para JWT (Mantenla segura en producción)
jwt.secret=4zBhS6W8mN5pQ9rTvY2xCbEfGhJkMnPqRsTuVwYzAbCdEfGhJkMnPqRsTuVwYzAb