spring.application.name=backend
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3307}/lecfantasy
spring.datasource.username=${DB_USER:fantasy_user}
spring.datasource.password=${DB_PASSWORD:fantasypassword}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver